# name: Build

# on:
#   push:
#     branches:
#       - test-ci
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@master

#       - name: Use NodeJS
#         uses: actions/setup-node@master

#       - name: Install dependencies
#         run: npm ci

#       - name: Build
#         run: npm run build
